name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Init gradle
        run: ./gradlew tasks --group=build
      - name: Run assemble task
        run: ./gradlew assembleDebug --stacktrace --no-configuration-cache